export const FLAG_AGGREGATE_TYPE = 'FLAG';

export const FLAG_COMMAND_REPOSITORY_DEPENDENCY_TOKEN =
  'FLAG_COMMAND_REPOSITORY_DEPENDENCY_TOKEN';

export const FLAG_QUERY_REPOSITORY_DEPENDENCY_TOKEN =
  'FLAG_QUERY_REPOSITORY_DEPENDENCY_TOKEN';

export const FLAG_VALIDATION_SERVICE_INJECTION_TOKEN =
  'FLAG_VALIDATION_SERVICE_INJECTION_TOKEN';
