export const SURVEY_REVIEW_AGGREGATE_TYPE = 'survey review';

export const SURVEY_REVIEW_COMMAND_REPOSITORY_INJECTION_TOKEN =
  'SURVEY_REVIEW_COMMAND_REPOSITORY_INJECTION_TOKEN';

export const SURVEY_REVIEW_QUERY_REPOSITORY_INJECTION_TOKEN =
  'SURVEY_REVIEW_QUERY_REPOSITORY_INJECTION_TOKEN';
