services:
  # In the future we will have one or more database nodes and potentially a messaging queue.
  # During development, we have injected an in-memory implementation of the persistence layer.
  # This is because choosing a concrete DB and implementing repositories is predictable work
  # and we want to tackle uncertain \ unknown parts of the system before committing to this work.

  api:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    env_file:
      - .env.${NODE_ENV}
    ports:
      - $API_PORT:$API_PORT
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3234"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  client:
    build:
      context: .
      dockerfile: apps/web-client/Dockerfile
    ports:
      - "$CLIENT_PORT:80"
    depends_on:
      api:
        condition: service_healthy # wait for health check
    networks:
      - app_network

    healthcheck:
      # TODO use env for port
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4200/"]
      interval: 15s
      timeout: 5s
      retries: 3

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
