services:
  # Note: If you are assigning a custom name to your db service on the line below, make sure it does not contain underscores
  # Currently, the `db` is only used for `SuperTokens`
  db:
    image: "postgres:latest"
    env_file:
      - .env.local
    environment:
      #   POSTGRES_USER: supertokens_user
      #   POSTGRES_PASSWORD: somePassword
      POSTGRES_DB: $AUTH_DB
    ports:
      - 5432:5432
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "supertokens_user", "-d", "supertokens"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:$POSTGRES_PORT/supertokens"
      API_KEYS: $SUPERTOKENS_API_KEYS
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    env_file:
      - .env.${NODE_ENV}
    ports:
      - $API_PORT:$API_PORT
    networks:
      - app_network

  client:
    build:
      context: .
      dockerfile: apps/web-client/Dockerfile
    ports:
      - "$CLIENT_PORT:80"
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
