export const TI_SYSTEM_USER_AGGREGATE_TYPE = 'system user';

export const TI_SYSTEM_USER_COMMAND_REPOSITORY_INJECTION_TOKEN =
  'TI_SYSTEM_USER_COMMAND_REPOSITORY_INJECTION_TOKEN';

export const TI_SYSTEM_USER_QUERY_REPOSITORY_INJECTION_TOKEN =
  'TI_SYSTEM_USER_QUERY_REPOSITORY_INJECTION_TOKEN';
