import { TrueImpactDataExample } from '../../../../../libs/data-types';
import { GROUP_PROGRAM_AGGREGATE_TYPE } from '../../constants';
import { GroupProgramCompositeIdentifier } from '../../group-program.composite-identifier';
import { GroupSessionLocationDto } from '../../group-session-location.value-object';

@TrueImpactDataExample<ScheduleGroupProgramSession>({
  example: {
    aggregateCompositeIdentifier: {
      type: GROUP_PROGRAM_AGGREGATE_TYPE,
      id: '123',
    },
    // TODO use proper dates
    date: '12-12-2012',
    location: {
      name: 'Williams Lake',
      isUrban: true,
    },
  },
})
export class ScheduleGroupProgramSession {
  static readonly type = 'SCHEDULE_GROUP_PROGRAM_SESSION';

  aggregateCompositeIdentifier: GroupProgramCompositeIdentifier;

  // TODO deal with dates properly
  date: string;

  location: GroupSessionLocationDto;

  // TODO startTime, endTime

  // session ID will be autogenerated
}
