export const GROUP_PROGRAM_AGGREGATE_TYPE = 'group program';

export const GROUP_PROGRAM_COMMAND_REPOSITORY_INJECTION_TOKEN =
  'GROUP_PROGRAM_COMMAND_REPOSITORY_INJECTION_TOKEN';

export const GROUP_PROGRAM_QUERY_REPOSITORY_INJECTION_TOKEN =
  'GROUP_PROGRAM_QUERY_REPOSITORY_INJECTION_TOKEN';
