export const COMMUNITY_AGGREGATE_TYPE = 'community';

export const COMMUNITY_QUERY_REPOSITORY_INJECTION_TOKEN =
  'COMMUNITY_QUERY_REPOSITORY_INJECTION_TOKEN';

export const COMMUNITY_COMMAND_REPOSITORY_INJECTION_TOKEN =
  'COMMUNITY_COMMAND_REPOSITORY_INJECTION_TOKEN';

export const COMMUNITY_VALIDATION_SERVICE_INJECTION_TOKEN =
  'COMMUNITY_VALIDATION_SERVICE_INJECTION_TOKEN';
