name: build

on:
  pull_request:
    branches:
      - integration
    
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    # TODO pin all actions to a specific SHA
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup Node.js 
        uses: actions/setup-node/@v6
        with:
          node-version: 24.13.0
      - name: Install back-end dependencies
        run: yarn install --frozen-lock-file
        working-directory: ./apps/server

      - name: Lint server
        run: npm run lint
        working-directory: ./apps/server

      - name: Build server
        run: npm run build
        working-directory: ./apps/server 

      - name: Unit test server
        run: npm run test
        working-directory: ./apps/server

      - name: Upload server artifact
        uses: actions/upload-artifact@v7
        with:
          name: server
          path: | 
            ./apps/server/dist
            ./apps/server/node_modules
          if-no-files-found:
            error

      - name: Start containerized app
        run: docker compose up -d --build
      - name: Wait for Docker health check
        run: 
          |
            until [ "$(docker inspect --format='{{.State.Health.Status}}' $(docker compose ps -q web-app))" == "healthy" ]; do
              sleep 3
            done
      
      - name: e2e test server
        run: npm run jest --runInBand
        working-directory: ./apps/server
      - if: always()
        run: docker compose down -v         