name: build

on:
  pull_request:
    branches:
      - integration
    
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    # TODO pin all actions to a specific SHA
      - name: Checkout code
        uses: actions/checkout@v4 
      - name: Setup Node.js 
        uses: actions/setup-node/@v4
        with:
          node-version: 24.13.0
      - name: Install back-end dependencies
        run: yarn install --frozen-lock-file
        working-directory: ./apps/server

      - name: Build server
        run: npm run build
        working-directory: ./apps/server 

      - name: Upload server artifact
        uses: actions/upload-artifacts@v4
        with:
          name: server
          path: ./apps/server/dist
          if-no-files-found:
            error
          