name: "Security Scan (CodeQL)"
on:
  push:
    pull_request: 
      branches
        - integration
        - staging
    schedule:
      - cron '0 0 * * 0' # Every Sunday at midnight

jobs:
  codeql:
    name: GitHub CodeQL Scan
    runs-on:
      ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Initialize codeql
        uses: github/codeql-action/init@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # 4.36.3
        with:
          languages: 'javascript-typescript'
          queries: security-extended,security-and-quality

      - name: Autobuild
        uses: github/codeql-action/autobuild@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # 4.36.3

      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # 4.36.3
        with: 
          category: "/language:javascript-typescript"

  semgrep:
    name: semgrep-scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run Semgrep Scan
        run: semgrep scan --config auto

  secret-scan:
    name: Secret & Dotenv Leak Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 0 # Deep history check

    - name: TruffleHog OSS Secret Scan
      uses: trufflesecurity/trufflehog-oss-action@main # TODO pin this to an SHA
      with:
        base: ${{ github.event.repository.default_branch }}
        head: HEAD
        extra_args: --only-verified

    # TODO dependabot