name: UI E2E

on:
  # We run on PR, but the check only gates moving beyond integration
  pull_request:
    branches:
      - integration
  push:
    branches:
      - integration

# note that we don't want to cancel concurrent runs as it can be helpful to know which push to `integration` broke the UI tests

permissions: {}

jobs:
  uie2e:
    runs-on: ubuntu-latest
    environment:
      name: e2e
    
    steps:
      # TODO use shared actions to share steps with other workflows
      # TODO pin all actions to a specific SHA
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Start containerized app
        env:
          POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          NODE_ENV: ${{ vars.NODE_ENV }}
          CLIENT_PORT: ${{ vars.CLIENT_PORT }}
          CLIENT_DOMAIN: ${{ vars.CLIENT_DOMAIN }}
          EVENT_STORE_DB_NAME: ${{ secrets.EVENT_STORE_DB_NAME }}
          API_DOMAIN: ${{ vars.API_DOMAIN }}
          API_PORT: ${{ vars.API_PORT }}
          TI_ENCRYPTION_KEY: ${{ secrets.TI_ENCRYPTION_KEY }}
          TI_COOKIES_SECRET: ${{ secrets.TI_COOKIES_SECRET }}
          SYSTEM_ADMIN_USERNAME: ${{ secrets.SYSTEM_ADMIN_USERNAME }}
          INITIAL_ADMIN_PASSWORD: ${{ secrets.INITIAL_ADMIN_PASSWORD }}
      # Note that we do not pass a .env file here. All secrets \ configuration comes from the GitHub environment.
      # # TODO do we need to set NODE_ENV like this?
        run: |
          NODE_ENV=$NODE_ENV docker compose config
          NODE_ENV=$NODE_ENV docker compose up --build
          NODE_ENV=$NODE_ENV docker network ls

      - name: Wait for Server
        run: npx wait-on "$API_DOMAIN:$API_PORT" --timeout 60000

      - name: Temp Diagnostics
        run : docker ps -a

      - name: Wait for Client
        run: npx wait-on $CLIENT_DOMAIN:$CLIENT_PORT --timeout 60000

      - name: Set Up Node.js
        uses: actions/setup-node/@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.13.0

      - name: Set Up ChromeDriver
        uses: browser-actions/setup-chrome@2e1d749697dd1612b833dba4a722266286fbefcd # v2.1.2
        with:
          chrome-version: '147.0.7727'

      - name: Install e2e npm dependencies
        run: yarn install --frozen-lock-file
        working-directory: ./apps/e2e

      - name: e2e test UI
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
          SYSTEM_ADMIN_USERNAME: ${{ secrets.SYSTEM_ADMIN_USERNAME }}
          INITIAL_ADMIN_PASSWORD: ${{ secrets.INITIAL_ADMIN_PASSWORD }}
        run: |
          yarn run wdio:ci
        working-directory: ./apps/e2e
      - if: always()
        run: |
          docker compose down -v
